import "vertex.idl";

namespace graphics
{
	struct view
	{
		UInt64 buffer_location;
		UInt32 size_in_bytes;
		UInt32 stride_in_bytes;
	};

	enum buffer_type
	{
		dynamic_buffer = 0,
		static_buffer = 1
	};

	[bindable]
	[default_interface]
	runtimeclass buffer
	{
		buffer();
		buffer(buffer_type type, Windows.Foundation.Collections.IVector<vertex> initial_data, Int32 max_size, Int32 resize_increment, Boolean is_auto_resize);
		view get_view();
		Int32 get_capacity_percentage();
		void add_to_view(vertex new_vertex);
		void clear();

		Int32 max_size;
		Int32 current_size;
		Int32 resize_increment;
		Boolean is_auto_resize{ get; };
		Boolean is_buffer_full{ get; };
	}
}
