import "buffer.idl";
import "shader.idl";
import "texture.idl";

namespace graphics
{
	enum primitive_types
	{
		points = 0,
		triangle_list = 1,
		triangle_strips = 2,
		line_lists = 3,
		line_strips = 4
	};

	enum compilation_status
	{
		success = 0,
		error = 1,
		cancelled = 2
	};

	struct compilation_result
	{
		compilation_status status;
		String error_message;
	};

	[default_interface]
	runtimeclass renderer : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		renderer();

		void enable_debug_layer();
		void initialize_buffers_showcase(Windows.UI.Xaml.Controls.SwapChainPanel target_swapchain);
		void initialize_textures_showcase(Windows.Foundation.Collections.IMap<String, Object> ui_items);
		void clear_shaders();
		void clear_textures();
		void remove_texture(String name);
		void remove_shader(String name);
		void start_render_loop();
		void stop_render_loop();

		Boolean is_rendering{ get; };
		primitive_types current_topology{ get; set; };
		Windows.Foundation.IAsyncOperation<compilation_result> pick_and_compile_shader(shader new_shader);
		Windows.Foundation.IAsyncOperationWithProgress<texture, String> pick_texture(graphics.texture new_texture, String name);
		buffer current_buffer{ get; set; };

		UInt32 viewport_width;
		UInt32 viewport_height;
	}
}
