import "buffer.idl";
import "shader.idl";
import "texture.idl";

namespace graphics
{
	enum primitive_types
	{
		points = 0,
		triangle_list = 1,
		triangle_strips = 2,
		line_lists = 3,
		line_strips = 4
	};

	enum operation_status
	{
		success = 0,
		error = 1,
		cancelled = 2
	};

	struct operation_result
	{
		operation_status status;
		String error_message;
	};

	[default_interface]
	runtimeclass renderer : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		renderer();

		void enable_debug_layer();
		void initialize_buffers_showcase(Windows.UI.Xaml.Controls.SwapChainPanel target_swapchain);
		void initialize_textures_showcase(Windows.UI.Xaml.Controls.SwapChainPanel target_swapchain);
		void clear_shaders();
		Windows.Foundation.IAsyncOperationWithProgress<operation_result, String> create_dds_textures(
			String name, 
			UInt64 width, 
			UInt64 height, 
			alpha_mode alpha_mode, 
			Boolean is_generating_mipmaps, 
			Boolean is_saving_to_file, 
			out IObservableVector<graphics.texture> new_textures);
		void clear_textures();
		void remove_texture(String name);
		void remove_shader(String name);
		void start_render_loop();
		void stop_render_loop();

		Boolean is_rendering{ get; };
		primitive_types current_topology{ get; set; };
		Windows.Foundation.IAsyncOperation<operation_result> pick_and_compile_shader(shader new_shader);
		Windows.Foundation.IAsyncOperationWithProgress<operation_result, String> pick_texture(out graphics.texture new_texture, String name);
		buffer current_buffer{ get; set; };
		texture current_texture;
		Int32 current_texture_index;

		UInt32 viewport_width;
		UInt32 viewport_height;
	}
}
