namespace graphics
{
	enum shader_type
	{
		vertex = 0,
		pixel = 1,
		geometry = 2
	};

	[bindable]
	[default_interface]
	runtimeclass shader : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		shader(String name, shader_type type);

		String shader_name;
		String file_name;
		String type_glyph;
		Boolean is_loading;
		Boolean is_error;
		shader_type shader_type;

		String compiler;
		UInt64 instruction_count;
		UInt64 version;
		UInt64 constant_buffer_count;
		UInt64 bound_resources_count;

		UInt64 texture_writes_count;
		UInt64 texture_load_instructions_count;
		UInt64 texture_normal_instructions_count;
		UInt64 texture_comparison_instructions_count;
		UInt64 texture_bias_instructions_count;
		UInt64 texture_gradient_instructions_count;

		UInt64 input_parameters_count;
		UInt64 output_parameters_count;

		IObservableVector<IInspectable> shader_reflection_data;
		IObservableVector<IInspectable> shader_bound_resources;
	}
}
