import "subresource.idl";

namespace graphics
{
	[bindable]
	[default_interface]
	runtimeclass texture : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		texture();

		String texture_name;
		String file_name;
		Boolean is_loading;
		Boolean is_error;
		Windows.UI.Xaml.Media.Imaging.SoftwareBitmapSource bitmap_source;

		UInt32 mip_levels;
		UInt32 width;
		UInt32 height;
		String dimension;
		UInt32 row_pitch;
		UInt32 slice_pitch;
		Single current_lod;
		Single scale;
		Windows.UI.Color sampler_border_color;
		Single sampler_minLOD;
		Single sampler_maxLOD;
		IObservableVector<IInspectable> mipmaps;

		Single topleft_u;
		Single topleft_v;
		Single topleft_x;
		Single topleft_y;

		Single topright_u;
		Single topright_v;
		Single topright_x;
		Single topright_y;

		Single bottomleft_u;
		Single bottomleft_v;
		Single bottomleft_x;
		Single bottomleft_y;

		Single bottomright_u;
		Single bottomright_v;
		Single bottomright_x;
		Single bottomright_y;
	}
}
