namespace graphics
{
    [bindable]
    runtimeclass texture : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
		texture();
		String texture_name;
		Boolean is_loading;
		Boolean is_error; 
		Windows.UI.Xaml.Media.Imaging.SoftwareBitmapSource bitmap_source;
    }
}
