// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/graphics.h"

namespace winrt::graphics::implementation {

template <typename D, typename... I>
struct WINRT_EBO buffer_base : implements<D, graphics::Ibuffer, I...>
{
    using base_type = buffer_base;
    using class_type = graphics::buffer;
    using implements_type = typename buffer_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"graphics.buffer";
    }
};

}

namespace winrt::graphics::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO bufferT : implements<D, Windows::Foundation::IActivationFactory, graphics::IbufferFactory, I...>
{
    using instance_type = graphics::buffer;

    hstring GetRuntimeClassName() const
    {
        return L"graphics.buffer";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }

    graphics::buffer CreateInstance(graphics::buffer_type const& type, Windows::Foundation::Collections::IObservableVector<graphics::vertex> const& initial_data, int32_t max_size, int32_t resize_increment, bool is_auto_resize)
    {
        return make<T>(type, initial_data, max_size, resize_increment, is_auto_resize);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_BUFFER_XAML_G_H) || __has_include("buffer.xaml.g.h")

#include "buffer.xaml.g.h"

#else

namespace winrt::graphics::implementation
{
    template <typename D, typename... I>
    using bufferT = buffer_base<D, I...>;
}

#endif
