// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/graphics.h"

namespace winrt::graphics::implementation {

template <typename D, typename... I>
struct WINRT_EBO shader_base : implements<D, graphics::Ishader, Windows::UI::Xaml::Data::INotifyPropertyChanged, I...>
{
    using base_type = shader_base;
    using class_type = graphics::shader;
    using implements_type = typename shader_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"graphics.shader";
    }
};

}

namespace winrt::graphics::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO shaderT : implements<D, Windows::Foundation::IActivationFactory, graphics::IshaderFactory, I...>
{
    using instance_type = graphics::shader;

    hstring GetRuntimeClassName() const
    {
        return L"graphics.shader";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        throw hresult_not_implemented();
    }

    graphics::shader CreateInstance(hstring const& name, graphics::shader_type const& type)
    {
        return make<T>(name, type);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_SHADER_XAML_G_H) || __has_include("shader.xaml.g.h")

#include "shader.xaml.g.h"

#else

namespace winrt::graphics::implementation
{
    template <typename D, typename... I>
    using shaderT = shader_base<D, I...>;
}

#endif
