// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once

#include "winrt/Windows.UI.Xaml.Controls.h"
#include "winrt/Windows.UI.Xaml.Data.h"
#include "winrt/graphics.h"

namespace winrt::graphics::implementation {

template <typename D, typename... I>
struct WINRT_EBO vertex_base : implements<D, graphics::Ivertex, Windows::UI::Xaml::Data::INotifyPropertyChanged, I...>
{
    using base_type = vertex_base;
    using class_type = graphics::vertex;
    using implements_type = typename vertex_base::implements_type;
    using implements_type::implements_type;
    
#if _MSC_VER < 1914
    operator class_type() const noexcept
    {
        static_assert(std::is_same_v<typename impl::implements_default_interface<D>::type, default_interface<class_type>>);
        class_type result{ nullptr };
        attach_abi(result, detach_abi(static_cast<default_interface<class_type>>(*this)));
        return result;
    }
#else
    operator impl::producer_ref<class_type> const() const noexcept
    {
        return { to_abi<default_interface<class_type>>(this) };
    }
#endif

    hstring GetRuntimeClassName() const
    {
        return L"graphics.vertex";
    }
};

}

namespace winrt::graphics::factory_implementation {

template <typename D, typename T, typename... I>
struct WINRT_EBO vertexT : implements<D, Windows::Foundation::IActivationFactory, graphics::IvertexFactory, I...>
{
    using instance_type = graphics::vertex;

    hstring GetRuntimeClassName() const
    {
        return L"graphics.vertex";
    }

    Windows::Foundation::IInspectable ActivateInstance() const
    {
        return make<T>();
    }

    graphics::vertex CreateInstance(float x, float y, float z, float r, float g, float b, float a, float u, float v)
    {
        return make<T>(x, y, z, r, g, b, a, u, v);
    }
};

}

#if defined(WINRT_FORCE_INCLUDE_VERTEX_XAML_G_H) || __has_include("vertex.xaml.g.h")

#include "vertex.xaml.g.h"

#else

namespace winrt::graphics::implementation
{
    template <typename D, typename... I>
    using vertexT = vertex_base<D, I...>;
}

#endif
