namespace wzrd_editor
{
	[default_interface]
	runtimeclass buffer_size_select_dialog : Windows.UI.Xaml.Controls.ContentDialog, Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		buffer_size_select_dialog();
		Int32 buffer_size{ get; set; };
		Boolean is_auto_resizeable{ get; set; };
	}
}
