import "Vertex.idl";
import "wzrd_vec3.idl";

namespace wzrd_editor
{
	runtimeclass Geometry : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		wzrd_vec3 Position{ get; };

		Windows.Foundation.Collections.IObservableVector<IInspectable> Vertices{ get; };
	}
}