import "Vertex.idl";
import "wzrd_vec3.idl";

namespace wzrd_editor
{
	[bindable]
	runtimeclass Geometry : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		wzrd_vec3 Position{ get; };
		Int32 Index{ get; set; };
		Int32 BufferCapacity{ get; set; };

		Windows.Foundation.Collections.IObservableVector<IInspectable> Vertices{ get; };
		Windows.Foundation.Collections.IObservableVector<IInspectable> Indices{ get; };
	}
}