import "Geometry.idl";
import "Shader.idl";

namespace wzrd_editor
{
	[bindable]
	runtimeclass GeometryViewModel
	{
		Geometry Geometry{get; };
		Windows.Foundation.Collections.IObservableVector<IInspectable> Shaders{ get; };
		Windows.Foundation.Collections.IObservableVector<IInspectable> Textures{ get; };
	}
}