namespace wzrd_editor
{
	enum ShaderType
	{
		vertex = 0,
		pixel = 1
	};

	runtimeclass Shader : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		String Name;
		String TypeGlyph;
		Boolean Loading;
		Boolean is_error;
		ShaderType Type;
	}
}
