namespace wzrd_editor
{
    [bindable]
    [default_interface]
    runtimeclass texture_showcase_vm : Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        texture_showcase_vm();
		Windows.Foundation.Collections.IObservableVector<IInspectable> textures;
		Windows.Foundation.Collections.IObservableVector<IInspectable> shaders;
    }
}
