namespace wzrd_editor
{
	[bindable]
	runtimeclass Vertex : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		Single x;
		Single y;
		Single z;

		Single r;
		Single g;
		Single b;
		Single a;

		Single u;
		Single v;
	}
}
