// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180821.2

#pragma once
#include "winrt/impl/Windows.UI.Xaml.Controls.0.h"
#include "winrt/impl/Windows.UI.Xaml.Data.0.h"
#include "winrt/impl/graphics.0.h"

WINRT_EXPORT namespace winrt::graphics {

struct WINRT_EBO Ibuffer :
    Windows::Foundation::IInspectable,
    impl::consume_t<Ibuffer>
{
    Ibuffer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IbufferFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IbufferFactory>
{
    IbufferFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO Irenderer :
    Windows::Foundation::IInspectable,
    impl::consume_t<Irenderer>
{
    Irenderer(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO Ishader :
    Windows::Foundation::IInspectable,
    impl::consume_t<Ishader>
{
    Ishader(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IshaderFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IshaderFactory>
{
    IshaderFactory(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO Ivertex :
    Windows::Foundation::IInspectable,
    impl::consume_t<Ivertex>
{
    Ivertex(std::nullptr_t = nullptr) noexcept {}
};

struct WINRT_EBO IvertexFactory :
    Windows::Foundation::IInspectable,
    impl::consume_t<IvertexFactory>
{
    IvertexFactory(std::nullptr_t = nullptr) noexcept {}
};

}
